### ISSUE TITLE
Upgrade to V2.37 or V2.38 Failed

### ISSUE THREAD

**Issue by WdrFafa** [alexed1/LightningFlowComponents#1102]
Hi,

I actually have the V2.36 of 'FlowActionsBasePack' on my org.
when i tried to upgrade it whether in V2.38 or V2.37 the installation failed with the following error message :
" Invalid Upgrade.
The currently installed version does not share a common ancestor with this version."
![image](https://user-images.githubusercontent.com/103574978/163198167-5e67b2bf-c8b7-4e97-964f-04d1bf2fc26d.png)

The steps to reproduce :
Check the version on the target org to update that should be V2.36
Go to  https://unofficialsf.com/flow-action-and-screen-component-basepacks/
Click on the version link, for exemple : https://test.salesforce.com/?ec=302&startURL=%2Fpackaging%2FinstallPackage.apexp%3Fp0%3D04t4W0000030AICQA2
Follow the salesforce screen steps : 
- >  Install for all users
- >  Check the warning box on a non salesforce application 
- >  Click on the 'Upgrade' CTA
![image](https://user-images.githubusercontent.com/103574978/163198697-6b5682a6-b2f1-40b5-bf7c-69445b640a33.png)

**Comment by alexed1** [comment]
You're going to want to go straight to the new V3 of the base packs, which should update over your existing code.

**Comment by Xtremefaith** [comment]
@alexed1 I have the same issue with version 2.2, I upgraded to 3.0 and because of the new namespace they are both installed. I don't quite know what this means for me. 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/1228550/170629916-e9c2cba6-5993-4125-bc33-8e0ca80a4e30.png">

I can't uninstall version 2.2 because the following dependencies. Is there a way to easily manage moving these resources to the new version so that I can remove 2.2? More importantly, what happens with components actively being used by screen flows? I've read through many comments about this challenge here but I've yet to find and documentation about how to manage this. Hoping with the release of 3.0 this is easier.
<img width="963" alt="image" src="https://user-images.githubusercontent.com/1228550/170630077-93b84a6d-f2ff-49b8-8b71-9503f67388bb.png">

Considering an upcoming deployment we have coming I'm a bit desperate to get this resolved by this weekend if at all possible. Thank you for everything you and your team have done to give us these tools, we really appreciate it.

**Comment by alexed1** [comment]
You don't need to upgrade version 2. Now that you have v3, use that. Focus on upgrading whatever else you have to v3 so it uses v3 base pack
