### ISSUE TITLE
Apex action error: unable to read sobject

### ISSUE THREAD

**Issue by pablogomez2197** [alexed1/LightningFlowComponents#1181]
Hello, we are trying to use the component to show the Order Product History in an Order tab. These are the steps:
1- First, we get the order record and we pass it to an apex class.
2- The flow gets the Order Product History records well and then we have the problem in the Screen element.
3- This is the element:
![image](https://user-images.githubusercontent.com/110610165/182849219-8ebba4bf-9531-4f20-8832-36eefc5b0658.png)
 And then when we choose a field of the object and click next this happens:
![image](https://user-images.githubusercontent.com/110610165/182849562-6eb2a65b-d1b5-46f4-983b-2477b507d40e.png)
This error appears and the table is empty. It happens with all the fields it does not matter which one you choose from this object.

We are sure that its with this object, because with the standard object Order didn't happens.

Thanks for your help.

**Comment by ericrsmith35** [comment]
Not all standard objects behave nicely.  For history objects, you will need
to format the records as a String or as Apex-Defined in order to display
them in the Datatable.  You can find some details on how to do that here:
https://ericsplayground.wordpress.com/how-to-use-an-apex-defined-object-with-my-datatable-flow-component/

**Comment by pablogomez2197** [comment]
Yes, that's what I saw on the internet. 
Thanks for the speed of the reply.
