### ISSUE TITLE
Getting error: Uncaught AuraFriendlyError: Custom Script Eval error

### ISSUE THREAD

**Issue by jlig** [alexed1/LightningFlowComponents#131]
I'm still learning "Flow" and building a "Create Record" flow that requires a lookup to my custom object "Items"
- I installed the lookupFSC v2.0 and added to my Screen
- I configured the fields:

Object Name: XX_Base__Item__c (this is a custom object)
Display Which Field: Item_Summary__c (this is a formula field)
Field Label: blank
Output Which Field as Value: Id
Where Clause: Administer_Group__c = False (this is a checkbox field)

- I then assigned the Flow to an Action Button on my page
- When I run the Flow on my page, it immediately pops up the following error:
Uncaught AuraFriendlyError: Custom Script Eval error [SecureDOMEvent: [object Event]{ key: {"namespace":"c"} }]

ps: Lightning Runtime has been enabled.
![2019-03-04_10-58-35](https://user-images.githubusercontent.com/1561704/53750994-e0c86700-3e70-11e9-8b66-984211f90d34.png)
![2019-03-04_11-31-01](https://user-images.githubusercontent.com/1561704/53751065-08b7ca80-3e71-11e9-9816-c96983b76abf.png)

**Comment by jlig** [comment]
I also get a second error when I try and select a value from the lookup drop-down:
Uncaught Action failed: c:LightningLookup$controller$hover [$ is not defined]

**Comment by mtagler-relativity** [comment]
I'm getting the exact same error. I had this working before, but had to pull it back down to my sandbox from GitHub using AutoRabit. We had to delete the FSC reference because it was causing the deploy to fail. When I rebuilt, I get the same error described above.

Error when opening flow screen with FSC
![image](https://user-images.githubusercontent.com/42183570/53837984-9c64c600-3f59-11e9-8ac7-8e6aa9e5f7f1.png)

Again when I click on the FSC component field
![image](https://user-images.githubusercontent.com/42183570/53838033-c3bb9300-3f59-11e9-9af1-2ec172000003.png)

Here are my inputs:
![image](https://user-images.githubusercontent.com/42183570/53838163-02514d80-3f5a-11e9-87ba-f18d10283d01.png)

**Comment by ericrsmith35** [comment]
Looks like an issue with jquery - I'll post a fix as soon as I can.

**Comment by ericrsmith35** [comment]
I've created a pull request (#132) with the fix for this error

**Comment by mtagler-relativity** [comment]
Thanks @ericrsmith35 . I went and downloaded again and configured and I'm still getting an error:
![image](https://user-images.githubusercontent.com/42183570/53975256-0b612c80-40ca-11e9-9257-6128b8ecfee4.png)

**Comment by ericrsmith35** [comment]
Mary - The source code update hasn't been enabled on Alex's GitHub site
yet.  The managed package is available to install here
<https://login.salesforce.com/packaging/installPackage.apexp?p0=04t1K000002ijQZ&isdtp=p1>
.

Alex - Looks like there is a dead link when you try to click through for
the lookup component.

**Comment by mtagler-relativity** [comment]
@ericrsmith35 Thanks for the quick response. I got it working, but am seeing this error when moving from my screen with the lookup to the next screen. Red warning toasts persist in the background and on the page after the flow finishes. Not sure if I'm missing something; since I'm using the new Flow Builder things look a bit different in the example, but it is working as I need it to.

![image](https://user-images.githubusercontent.com/42183570/53996654-e6d37780-40fe-11e9-90aa-812cef5d067d.png)

**Comment by jlig** [comment]
I'm getting same error as Mary.. but the record does get created correctly!
<img width="608" alt="2019-03-08_16-33-40" src="https://user-images.githubusercontent.com/1561704/54060096-1945a900-41c1-11e9-8088-ef31a8a8d920.png">

**Comment by jlig** [comment]
One more small issue:
<img width="759" alt="2019-03-08_17-05-22" src="https://user-images.githubusercontent.com/1561704/54061102-eb626380-41c4-11e9-9912-9ad52f4c9e3e.png">

**Comment by mtagler-relativity** [comment]
Same for me too @jlig

**Comment by ericrsmith35** [comment]
A fix that removes jQuery has been applied.  Change the API version of the code to 38.0 to avoid the $A.getEvt error.
