### ISSUE TITLE
Look into GetRandomNumber test failure

### ISSUE THREAD

**Issue by alexed1** [alexed1/LightningFlowComponents#1376]
happened when tried to build a new version using PR https://github.com/alexed1/LightningFlowComponents/pull/1371

Version create.... Create version status: Error
Error (1): Multiple errors occurred: 
(1) Apex Test Failure: Class.GetRandomNumberTest.numberAboveOneGeneratedIsInRange: line 49, column 1 System.AssertException: Assertion Failed: Expected: true, Actual: false

**Comment by mtptb** [comment]
Hi @alexed1 ,

I checked the unit test class _GetRandomNumberTest_ and I found the root cause about assertion fail.
In the the method **_numberAboveOneGeneratedIsInRange_** the startNum has value 5, the same of resultNum return by _**generateRandomFromRange**_. 
The assertation _System.assertEquals(true, resultNum>startNum);_ cannot be true due the equality operator defined as '>'

![image](https://user-images.githubusercontent.com/39939267/227904690-11f665ac-d0b7-4348-b8e1-50f19499c46b.png)
![image](https://user-images.githubusercontent.com/39939267/227904762-a018511f-9c2e-4a06-91ac-6bea6980518a.png)

I think that the assertation should check if the resultNum is '>=' of startNum and '<=' of endNum.

What do you think?

**Comment by alexed1** [comment]
so it never could have worked at all? wow. Would it be convenient for you to create a PR to fix that test?

**Comment by mtptb** [comment]
It could work when the number returned is in range but not equal to start and end limits.
I can fix it and then I will send a pull request with this.

**Comment by mtptb** [comment]
Hi @alexed1 , you have a new PR #1379 to merge and fix GetRandomNumberTest class.

**Comment by alexed1** [comment]
https://unofficialsf.com/working-with-the-site/flow-action-get-random-number/
