### ISSUE TITLE
Reactive collection processor : perf improvement and less dependency 

### ISSUE THREAD

**Issue by dufoli** [alexed1/LightningFlowComponents#1480]
**Is your feature request related to a problem? Please describe.**
- Avoir need of https://unofficialsf.com/list-actions-for-flow/ dependency
- performance improvement
 
**Describe the solution you'd like**
- switch action collection processor to pure javascript by using map(), filter(), reduce(), sort(),...

**example with extractFieldToCollection **
```
extractFieldToCollection() {
    if (this.inputRecordCollection == null) {
        return null;
    }
    if (!this.fieldAPIName) {
        return null; // fieldname is required
    }
    const UniqueSet = new Set();

    this.fieldValueCollection = this.inputRecordCollection.filter(rec => !this.dedupeDefault || !UniqueSet.has(rec[this.fieldAPIName])).map(rec => {
    UniqueSet.add(rec[this.fieldAPIName]);
    return rec[this.fieldAPIName]
    });

    this.fieldValueString = this.fieldValueCollection.join(',');
}

```
@ericrsmith35

**Comment by ericrsmith35** [comment]
I realize that standalone LWC components can perform the same actions but
what I'm trying to do with this group of components is to show how LWC can
be used to take advantage of any existing Invocable Actions.  Because of
that, I would like to leave these as is.  However, there is definitely room
for a whole new separate collection of LWC actions that can act on record
and/or text collections.
