### ISSUE TITLE
*Datatable* - Apex Definied collection doesn't work since spring 24 (API60)

### ISSUE THREAD

**Issue by FabLeroux** [alexed1/LightningFlowComponents#1516]
Hi,

We use your datable component V4.1.4 and in one of our flow which Api version is 59 with Apex defined Collection.
Since Spring 24 it doesn't work anymore without any other modification
The error provided is "Cannot read properties of undefined(reading 'fieldname')
![Capture d'écran 2024-02-05 111429](https://github.com/alexed1/LightningFlowComponents/assets/103574978/4fe8c3da-f306-4f95-b293-62a44a4380eb)

**Comment by ericrsmith35** [comment]
I'm unable to reproduce this behavior.  Please share how you have the Datatable configured.  Also, please try building a new flow to display similar Apex Defined data and see if that fails as well.

**Comment by idrissbe5** [comment]
Hi Eric, 
I work with FabLeroux on that project. 
I tried looking for a solution on that issue. 
the issue was located on the line : 928
![image](https://github.com/alexed1/LightningFlowComponents/assets/124882248/29531ac0-eec5-4464-bf05-3fe3a99f0ae6)
![image](https://github.com/alexed1/LightningFlowComponents/assets/124882248/5e842d57-42bf-49a0-b0e7-7cbc43061c56)

To prevent the undefined case i added on the condition 'if(this.cols[0] != '')' a : '&& this.cols[0] != null'
I don't if you had a similar issue, or someone had the same as us. 
I didn't do all the tests to be sure that this udpate solved well the issue but it seems to work

If this isn't supposed to be undefined, do you have an idea of what happened or do you need more info ? 

Best Regards
Idriss Belaid

**Comment by ericrsmith35** [comment]
@idrissbe5 what you suggested as a fix doesn't match the image of the code changes you included.  Can you please provide a little more detail?

**Comment by idrissbe5** [comment]
the images that i added are the issues shown, my suggested fix is this : 
<img width="448" alt="image" src="https://github.com/alexed1/LightningFlowComponents/assets/124882248/42fbcb4e-a1db-458a-9c54-aa8ab80de014">

**Comment by ericrsmith35** [comment]
Would this work instead?

![image](https://github.com/alexed1/LightningFlowComponents/assets/24724447/26bafee0-dd24-4257-a912-4f7bac11746d)

**Comment by idrissbe5** [comment]
I will test it and see, as soon as i tested it i will notify you
