### ISSUE TITLE
"Invalid ID field: Id" on Parent / Child Lookups

### ISSUE THREAD

**Issue by iamlukeamiller** [alexed1/LightningFlowComponents#152]
We're getting an exception thrown by LightningController.cls by a pair of flowFSC lookups on a single screen. One is set up as the Parent (using the custom object WB_Client__c), and one is the Child (using the custom object WB_Project__c). 

The error reads as follows: 

`"EXCEPTION_THROWN [134]|System.QueryException: invalid ID field: Id"`

Interestingly, the exception doesn't actually _stop_ anything from processing and the final record that comes out of the flow has the two lookups set correctly. Just throws a big red error to the user.

For reference, below are the inputs for both lookup components:

**Parent (WB_Client__c):**

```
API Name: WBClientLookup
Component ID: WBClientLookup
Default Value: 
I1_Object Name: WB_Client__c
I2_Display Which Field? Name
I3_Field Label: Client
I4_Output Which Field as Value? Id
I5_ Parent or Child Lookup? Parent
I6_Filter on which field? Id (not filtering, but ensured this was a field actually on the record as it seems to default to "AccountId" if I attempt to leave it blank)
I7_Filter Value: 
(Input Section) O1_Output Value: Id
(Output Section) O1_Output Value: {!v_WbClientId} (a text variable)
```

**Child (WB_Client__c):**

```
API Name: SelectProject
Component ID: SelectProject
Default Value: 
I1_Object Name: WB_Project__c
I2_Display Which Field? Name
I3_Field Label: Project
I4_Output Which Field as Value? Id
I5_ Parent or Child Lookup? Child
I6_Filter on which field? Id (same issue as above for this attribute)
I7_Filter Value: blank
Parent ID: WBClientLookup
(Input Section) O1_Output Value: Id
(Output Section) O1_Output Value: {!v_WBProjectID} (a text variable)
```

Unsure of what is causing the exception, wanted to check if this has happened to others and if there's a solution.

**Comment by ericrsmith35** [comment]
I6_Filter on which field? is ignored if there is no value provided for I7_Filter Value.

The error is most likely caused by "(Input Section) O1_Output Value: Id".  Populating that parameter on Input provides a default value to be returned for O1_Output Value in the Output section if no record is selected.  You should just leave that blank.

**_Here is an example of using Default Value and O1_Output Value on the input side:_**

Provide INPUT values for the following two parameters:

**Default Value:** (whatever placeholder text you want displayed in the input box)
**O1_Output Value:** The value to be passed out through the O1_Output Value OUTPUT parameter if no value is selected in the input box

Example:  Looking up an Account, defaulting to the Account Name of "ACME Company".  Assume the RecordId for ACME Company is stored in the flow variable vDefaultId.

**[Input Section]**
API Name: AcctLookup
Component ID: 
**Default Value: ACME Company**
I1_Object Name: Account
I2_Display Which Field? Name
I3_Field Label: Account
I4_Output Which Field as Value? Id
I5_ Parent or Child Lookup? 
I6_Filter on which field? 
I7_Filter Value: 
**O1_Output Value: {!vDefaultId}**

**[Output Section]** 
O1_Output Value: {!vSelectedAccountId} (a text variable)

**Comment by alexed1** [comment]
ok to close this?

**Comment by iamlukeamiller** [comment]
Yep, Eric's response was exactly what I needed. Thank you!

**Comment by SandyHunter** [comment]
Wow. I am stuck and need your help, SuperFlow people.
I'm working with the Unofficial LookUp Component, and trying to make a parent/child combo of components on a single screen.
For some reason I keep getting this error: "Exception occurred: invalid ID field: Id Class.LightningLookupController.getFieldValue: line 141, column 1"
I took a deep dive and realized I was using an older version of the component. Okay, I tell myself, and go through the process of getting the latest component into the sandbox. Still getting the error.
The first component is a look up to the account, the second is a lookup to a child contract record. 
Here's the kicker, I'm still getting the error message, but if I carry through the flow, the records still get created as they should. 
That said, the error message will throw off my end users. Can anyone help me out on this?
Thanks,
-Sandy
