### ISSUE TITLE
Enhancement: make it possible to assign the output of the Rich Text Input component to a field of type Rich Text Area

### ISSUE THREAD

**Issue by RuthReeseySmith** [alexed1/LightningFlowComponents#219]
I installed the Rich Text component https://unofficialsf.com/rich-text-input/  in my sandbox and trying to use in a flow screen and create record. I can add to screen just fine but when I try to set it as a value in my create record I get an error saying "The data type of the resource you entered isn't compatible." The field I am trying to set it to feed into is a rich text field. 
![image](https://user-images.githubusercontent.com/58233712/70455315-14789300-1a7a-11ea-8a4c-01399e770839.png)
![image](https://user-images.githubusercontent.com/58233712/70455350-24907280-1a7a-11ea-929d-bdd388fb295d.png)
Forgive me if I have done this wrong. I am new to GitHub.

**Comment by alexed1** [comment]
You haven't done anything wrong. The rich text support in flow isn't quite the same thing as a Field of type Rich Text Area, and they aren't interchangeable. I don't think it will take much work to the component to support this use case, but it isn't there today.

**Comment by RuthReeseySmith** [comment]
Hi Alex
Just saw this email from you. I did get this to work - found that the issue
was that when I chose the input field as a resource to create my record the
flow kept offering me the label name I assigned the component- I needed the
labelname.value. It is a issue with the flow though - I really had a hard
time getting the whole thing in the create record field. It wouldn't let me
select it. And I had to use it multiple times so once I got it right once,
I just pasted in other places.

Like this {!Describe_the_request.value}
Not this {!Describe_the_request}

**Comment by megmoo** [comment]
@RuthReeseySmith - I'm trying to do what I think you managed to do. I have a screen with the component on it. I have set the API Name of the component to be Enter_Rich_Text, then I set the record update field value to {!Enter_Rich_Text.value}, but I get the error "{!Enter_Rich_Text.value} isn't a valid merge field." Did you encounter that error? Any ideas of things to try? Thank you!

**Comment by DMarx-UWW** [comment]
@megmoo @RuthReeseySmith - I am also encountering the same issue, when I try to use the output of this component into the Body of the "[Send Rich (HTML) Email](https://unofficialsf.com/send-rich-email-with-the-new-sendhtmlemail-action/)" 

Thank you all for helping to steer us into the correct direction.

**Comment by RuthReeseySmith** [comment]
Yes but the .value is what worked for me. So mine
was {!Describe_the_request.value} because Describe the request was what I
named the input field

**Comment by alexed1** [comment]
Here are a couple of things that may help clear things up:
1) I've published a new 1.51 version here: https://unofficialsf.com/rich-text-input-flow-screen-component/
2) When you add this component (and other lightning components) to a flow screen, pay attention to the 'Manually Specify Variables' checkbox at the bottom of its property editor.  Right now we have that on by default for all new lightning screen components in order to avoid some problematic behavior that's described [here](https://unofficialsf.com/optimizing-lightning-component-inputs-and-outputs-in-flow-screens/).  If it's checked, you need to go down the classic path of defining a variable of type Text and mapping the value property of your rich text area control to it. You can then use the variable in a downstream Display Text. 

Alternatively, click off Manual mode and allow Flow to manage the mappings for you. If you do that you'll see a reference to the rich text that you can select when you click on the combo box in the downstream display text. 

In Summer '20, we expect to resolve the problematic behavior involving Previous and Next interactions with Automatic Output Handling. At that point, we'll default the checkbox in automatic mode.

**Comment by megmoo** [comment]
Thanks, @alexed1! That change now allows me to reference the output from the field.
