### ISSUE TITLE
Send HTML Email: Add automatic history recording

### ISSUE THREAD

**Issue by alexed1** [alexed1/LightningFlowComponents#270]
Implement the solution below. add a boolean attribute to let user specify whether they want to log the email, and make sure it handles cases where no recordId is provided.

Megan Moody says:(Edit)
January 10, 2020 at 9:08 am
What I ended up doing was adding the following to the code below setting of the subject:

// Log the email to the feed of the record
mail.setWhatId(recordId);

Because of the business requirements, I needed to log the actual email sent to the user. The above did that. Thank you!

**Comment by jdpond** [comment]
Proposed enhancement.
Using the SendHTMLEmail, you can send emails in a selected language using the localized version of and email template. I’ve forked a project for our own use but If there’s interest, I’d be glad to contribute the work.

For details, see https://github.com/jdpond/LightningFlowComponents/blob/master/flow_action_components/SendHTMLEmail/README.md

and https://github.com/jdpond/LightningFlowComponents/projects

**Comment by jdpond** [comment]
Alex, I'm a newb when it comes to contributing in this environment, so please bear with me - or refer me to others who can help.  I wrote this to solve our problems, generalizing it is going to take some work, which I'm glad to do.  Let's start with your advice:
"We’ll want to make sure that if a user doesn’t provide a value for this, then it will always be disregarded so that people can remain completely ignorant of it."

1. The generic issue of recordId fix above already exists in the proposed solution:
`        if (recordId != null) mail.setWhatId(recordId);`
2. I am using this in a Community Context - for good or for bad, it will not function in anonymous user context and I would like your feedback on this, ergo:
`public without sharing class SendHTMLEmail`
3. I've made some changes to some of the invocableVariable Description text for purely editorial reasons - would like your feedback on that too.
4. I changed the the label of invocableVariable recordId to 'Template WhatId' - not that I think it's better, but because that makes it consistent with other sendEmail documention.  I don't think this will impact existing users, but that should be considered.
5. (here's the REAL newb part)  In the test class I've added the creation of records - something I'm generally loathe to do because (for example) if you try and add a record and the installing org has a custom field that is required, the insert will fail.  So this poses two questions:
    a) For coverage testing of added code the addition of the test EmailTemplate records is required (see @testSetup static void testSetupdata()), Q:  Leave those tests in and risk future org defined required fields?
    b) I generated a linked record set (contact and case) to test the WhatId merging - a functional test versus a code coverage test.  This doesn't actually test the code added, so I'm thinking delete those tests which would allow me to delete the generated Contact/Case records?

**Comment by alexed1** [comment]
Great questions
1. By 'proposed solution', do you mean your most recent pull request?....it sounds like you're on top of implementing this, which is great. It still should probably be something that users opt into via an exposed boolean attribute that they can toggle in the property editor in Flow Builder.
2. That's a good one. I don't know if adding Without Sharing will cause any headaches, so I'd prefer to get the rest of your code but not change the class to Without Sharing. 
3. I think your descriptions are good. You're going to need to also have that information in the main documentation, so you have to balance the necessity to keep them in sync as things change with the desire to get more into the description.
4. I like to try to make sure the variable name conveys the purpose. This recordId is being used for logging history right? Do you think something like  Log To Which Record? might work?
5. I like your professionalism on the testing issue. I would say don't worry about future changes. Things like that (field that wasn't required becomes required) are rare on Salesforce because of the emphasis on not breaking existing implementations. If it does happen, we can rev the test. 
For the quality bar we normally shoot for, it's not necessary to have 100% test coverage. I don't want to keep you from adding them, but it's normal for there to be some lines that don't get tested.

**Comment by jdpond** [comment]
Alex, Thanks for the feedback - and you've given me far too much credit.

Synopsis:
1) Will do this
2) Will use CPE for proposed release(params to complicated for practical use - already too complex)
3) Would like to use "Without Sharing" - our app won't work without it (right now)
4) recordId is used for logging, activity, AND WhatId (relatedTo Merge Fields) - need further instruction
5) Will trim Test Class to remove related Contact/Case, but leave EmailTemplate Records Creation

1. Haven't made a pull request, just forked it - at the time wasn't sure this functionality was contributable.  HOWEVER, the forked functionality went into our production org last night.  Which is why SendHTMLEmail versus SendRichEmailCPE.  E.g., CPE isn't available until {{{Safe Harbor}}}.  Thanks for turning me on to CPE.  Before doing pull request, will develop CPE version which "toggles in property editor" - the correct solution.  Discussed with Tim Perdue, this Action component is already too complicated, more visible params aren't going to help.  and CPE can help resolve that, but can't use it in production until {{{Safe Harbor}}}.
2. "Without Sharing".  I know our application will not work (tested today) - the flow context is from Guest Community User.  While that shouldn't make a difference (it didn't matter for email alerts, but did for Flow Apex Action), it does.  Will investigate further about Sharing setup, but strongly suspect more related to accessibility of template in Community Context and/or ParentId - further investigation required.
3. Will document - assume using Readme.md, but a quip document works much better
4. recordId is used in multiple functions, including activity, history, and the "relatedTo(WhatId)" object in classic versions.  We use the "relatedTo" in many of our template communications.  Will keep it as a single parameter, but name should reflect all three?
5. Will pare down the test class to remove linked Contact/Case related tests, but retain the two EmailTemplate Records creation (right now, no such thing as custom fields on EmailTemplate)

**Comment by alexed1** [comment]
If you want to add this to the CPE version of Send Rich Email, that's fine. Note that usage of the CPE version will require pilot enablement via a request to Support until Summer '20 ships in June. At that point, we'll cut everyone over. If you're feeling it, create a pull request for both versions.

I've added you as a collaborator to the main repo, fyi. 

Let's try it "Without Sharing" and see if it causes anyone any problems. It will be a good learning experience.

The input param variable name should definitely stay "recordId" (I was wrong). As for the label, as long as the only purpose of passing a recordId into this action is to access templates effectively (because they're object-specific and their instances are linked to individual records), the label should be something like "Associated Record Id (for Template Use)". The logic is that the label should be as specific as possible. If we add some other use for recordId, we'd have to use a more general label.

To be consistent with the rest of the extensions, the main documentation that admins see should continue to be on this Wordpress page: https://unofficialsf.com/send-rich-email-with-the-new-sendhtmlemail-action/  In isolation, Quip might be better but there's a lot of benefit to working within the structure of the Wordpress site when it comes to admin-facing docs. To that end, I'll happily give you Editor access to update the existing page (I'll need an email address), or you can just give me the content and I'll update it. 

cheers,
alex

**Comment by jdpond** [comment]
I did the pull request on a dirty branch (extraneous commits, the final commit is actually accurate).  Cleaning it up now and will reissue
