### ISSUE TITLE
Required = True

### ISSUE THREAD

**Issue by kensation** [alexed1/LightningFlowComponents#29]
This is more of a general question. I understand that when you set the required attribute to true it's just adding the required styling to the field.  How would we go about actually making the field required if we are using Visual Flow and Screens?

**Comment by datapharmer** [comment]
I feel like this may be a recent bug as I swear this worked for me in the past but just experienced the same issue with the lookup component. It is possibly a bug from a recent code update or possibly introduced in summer 18. What component are you using? Can anyone else confirm this worked for them previously?

**Comment by alexed1** [comment]
You can't technically enforce a Required validation 100% of the time. The problem is that if the user simply clicks the Next button of the screen without interacting with your component, your component will have no way of finding that out, so it will have no way to yell "stop! I do not approve this transition!"

You can provide partial validation coverage by using your components onBlur events and trying to check when focus leaves your component, but it won't be reliable.

We have this on our roadmap to fix. The fix will involve the Flow Runtime calling your component and asking permission to transition. At that point you can validate your state and either say yes or no.
