### ISSUE TITLE
sendHTMLEmail - Activity History Redesign?

### ISSUE THREAD

**Issue by jdpond** [alexed1/LightningFlowComponents#320]
the saveAsActivity parameter is used not only for creating an email activity, but also creating a completed task.

The argument only applies as an email activity if the recipient list is based on targetObjectId or targetObjectIds in a template.  The saveAsActivity parameter creates a Task for the recordId passed in sendHTMLEmail.  I'd like to revisit this to see if there's a way to clarify and extend this functionality based on the request received below, but don't want to make the component any more complex than it already is.  The request was:

1. Is there any way to register the activity exclusively in the contact? I tried to put a contact ID in the whatid but it rejects it, so i have to choose another object to get the activity posted (in my case Recurring Donations object).
2. Is there a possibility to create just the email activity record (grey one) and not the activity (task)?

**Comment by alexed1** [comment]
When Summer 20 hits in June we're going to switch over to a CPE version of this. (https://unofficialsf.com/custom-property-editor-developer-toolkit-and-pilot-now-available/) This will immediately and radically simplify the configuration experience. That gives us a lot more room to add complexity, because from the point of view of the user, it might just show up as a couple of checkboxes in an "Advanced" section of the property editor, or something like that. 

I'm not very experienced with the Tasks and Activities part of the product.... What's the practical difference between an 'email activity' and a 'task' that can be 'completed'?  

You might want to start by figuring out what the ideal  UI would be, assuming all the functionality was present, and then work backwards from there.

**Comment by littlefishsolutions** [comment]
Alex,  I have been working on using your solution/product for that last month and this is a pain point to be able to reduce the clutter on the activity timeline.  I would also like to turn it off!
BTW... I love this solution.  Thanks to both of you for your community contribution.

<img width="221" alt="Tasks and Activities from SendHTMLEmail flow" src="https://user-images.githubusercontent.com/12245488/79602640-77c1a400-80b0-11ea-86d6-8ea865d16fe5.PNG">

The **EmailMessage** object stores all the information I need as a user (EmailBody, Recipients, pdfAttachments, HTMLTracking status)
The **Task** object, at least for our org is rarely used however is meant for followups for sales reps to burn down their list and typically show up on the organization home page in LEX.

You are probably very familiar already with the objects and maybe i missed your point.  Just trying to show you the clutter that it creates on the record activity timeline.

**Comment by alexed1** [comment]
Nah, I'm pretty ignorant about this stuff, so this is good learning.

I think I get it now. We handle a true input saveActivity by both setting the mail.saveAsActivity (which results in an EmailMessage object being generated and by manually creating a closed task. 

Yeah, as part of the Summer '20 upgrade, let's split this into two attributes and expose them as checkboxes on the nice new custom property editor.
