### ISSUE TITLE
Multiple Where clause parameters

### ISSUE THREAD

**Issue by gconarton** [alexed1/LightningFlowComponents#39]
I'm having an issue with a multiple where clause. 

My where clause is:

RecordTypeId = '012410000012dFjAAI' OR RecordTypeId = '012410000012ftqAAA' AND Active__c = 'True'

I get records with the two record type portions of the where clause but none when I add the boolean portion.

No results are returned to the dropdown list.  Suggestions?

Thanks!

**Comment by datapharmer** [comment]
your query is sending string data for other data types such as bool because of the quotes which means there are no matches. 

For example, assuming Active__c is true or false boolean/checkbox it should be: 
AND Active__c = true 
not 
AND Active__c = 'True'

The first one means the condition is true or checked while the second asks if the field equals the string "True" which it never can because the field type does not support a string value.

Start with each condition individually and debug to make sure you get a set of results and then add the ands and ors to combine them

**Comment by gconarton** [comment]
Thank you!
