### ISSUE TITLE
You do not have access to the Apex class named LightningLookupController

### ISSUE THREAD

**Issue by elmord73** [alexed1/LightningFlowComponents#496]
Hi!

I think it happened since winter21 release.
When I use a flow using LookupFSC (2,2 Managed) with a user that is not an admin, I get this error.
**You do not have access to the Apex class named LightningLookupController**

I can't add this code to the Profile (I read it is something to do with the fact it is not Global),

In porduction, no problem. I'm afraid it will also occur there when winter21 reach production.

Please help!!

Thanks!

**Comment by ericrsmith35** [comment]
There is a Critical Update in Winter '21 that now requires users to have a Profile or Permission Set permission for each @AuraEnabled Apex method used by Aura and Lightning Web Components.

Learn how to address this issue here: https://admin.salesforce.com/blog/2020/critical-update-ensure-users-have-access-to-auraenabled-methods

**Comment by elmord73** [comment]
Thank you for the quick and helpful response!!!
