### ISSUE TITLE
SendRichEmail -contentDocumentAttachments in flow LWC- collection type is false while it should be true

### ISSUE THREAD

**Issue by edmondo1984** [alexed1/LightningFlowComponents#568]
I think from the docs found here https://unofficialsf.com/send-better-email-examples/#Example3

this seems to be a typo, it should be a true
https://github.com/alexed1/LightningFlowComponents/blob/f07786c52cbb6537688e905f24321c7668ebf20e/flow_action_components/SendHTMLEmail/force-app/main/default/lwc/sendHTMLEmailCPE/sendHTMLEmailCPE.js#L71

**Comment by edmondo1984** [comment]
![Screenshot 2021-01-11 at 20 11 18](https://user-images.githubusercontent.com/812841/104227126-3268b200-5449-11eb-9a2e-8a9e8711e826.png)

**Comment by jdpond** [comment]
Does this problem exist in sendBetterEmail?

**Comment by edmondo1984** [comment]
Yes, it's a problem with sendBetterEmail. I had to work directly on the xml of the flow because I could not modify the flow variable in the widget

**Comment by jdpond** [comment]
The problem here is the default value of the parameter is false, when the default parameter in the Messaging Class is true, and CPE automatically defaults all Boolean Checkboxes to false(NULL).  The way we "fixed" this was to create a "new" component (sendBetterEmail) and documented that the default WOULD be false and that any existing usage would have to be manually edited for this.  However, I'm not sure this works in all of the 7 use cases we uncovered during this process (as a matter of fact, since 'false' is presented as a string value '$GlobalConstant.False' (which would be a logical TRUE).

Since then, @ericrsmith35  came up with a solution which has been implemented for World Wide United Way and they are in the process of testing it.  If this works, I can revisit the existing Boolean parameters to force parameter defaulting

Will update here after further exploration.

**Comment by jdpond** [comment]
Sorry,  my previous post was meant for another issue.  Could you check and make sure the parameter you are passing has "allow multiple values (collection)" checked?
![image](https://user-images.githubusercontent.com/271131/104744719-36cbee00-571b-11eb-9a27-61e60988e771.png)

**Comment by munawirrahman** [comment]
hi @jdpond any updates about this? Im still not able to find the contentdocument collection records variable in the action

**Comment by munawirrahman** [comment]
I dont know how, but im able to workarround this by changing to
`contentDocumentAttachments: {value: null, valueDataType: null, isCollection: true, label: 'Attach which Content Document Links?'} `

**Comment by jdpond** [comment]
This bug was discovered and (I believe fixed) in [Send Richer Email with the ‘Send Better Email’ Flow Action](https://unofficialsf.com/send-better-email-flow-action/) Pull #601 The problem was having an empty description field on the email template.  If you put anything in that description field, this bug will not occur, but was fixed anyway.

**Comment by mcculloughcm** [comment]
Hi @jdpond, I don't think this issue is fixed yet. I have 2.1 installed and I'm still seeing it.

I have a collection variable of CDLs:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/1189915/111710826-ac316900-8807-11eb-9b11-e6ca0f698e79.png">

But I can't select that collection variable in the Attachments field of the widget. The only options available to choose are single record variables. Here are the options I can choose from:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/1189915/111710972-03373e00-8808-11eb-8327-579cca011e02.png">

As you can see, those are all single record variables:
<img width="311" alt="image" src="https://user-images.githubusercontent.com/1189915/111711134-50b3ab00-8808-11eb-8cbb-312e600d1136.png">

**Comment by jdpond** [comment]
I just tested this using example 3 of Send Better Email Testflow successfully:  Email Received was:

![image](https://user-images.githubusercontent.com/271131/111723112-6beade80-8839-11eb-851b-b30f87028a3f.png)

I will try and replicate your problem tomorrow

**Comment by mcculloughcm** [comment]
Yes, that works fine for me as well. But if you try to change the filtered_cdls collection it's using in the example, you'll see that you can't choose another collection -- your only option is single record variables. If you change to a single record variable and then try to re-select the collection variable, you can't.

As @edmondo1984 said in the original ticket, it looks like the issue is here -- isCollection should be set to true: https://github.com/alexed1/LightningFlowComponents/blob/f07786c52cbb6537688e905f24321c7668ebf20e/flow_action_components/SendHTMLEmail/force-app/main/default/lwc/sendHTMLEmailCPE/sendHTMLEmailCPE.js#L71

**Comment by danielbprobert** [comment]
I'm having the same issue, I can't select a collection of contentdocumentlinks, I can select a single but then I get the error telling me it's not a collection.

![image](https://user-images.githubusercontent.com/3979761/112467984-a388e780-8d5f-11eb-8e13-9e63e2e46759.png)

![image](https://user-images.githubusercontent.com/3979761/112468046-b7cce480-8d5f-11eb-9c1c-e919fbcc0b93.png)

this doesn't happen in the example but does anytime I try to create a new one and send in attachments - running the latest version
