### ISSUE TITLE
SendBetterEmail - CPE - Task Always Created When a Related Record ID Is Included & Save Email as Activity Is Checked

### ISSUE THREAD

**Issue by Garywoo** [alexed1/LightningFlowComponents#831]
When creating a new SendBetterEmail action with a value in the "_Related Record Id_" field, and the checkbox for "_Save Email as Activity on Recipient Record(s)?_" is checked, a new task will still be created on the related record, even though the checkbox "_Save Email as Task on recipient related record(s)?_" has been left blank by default.

If you first check the _Save Email as Task_ box, click Done, then edit the action and uncheck the box again, the task is no longer created.

The issue appears to similar to that described in [this comment](https://github.com/alexed1/LightningFlowComponents/issues/702#issuecomment-859802728) in issue #702

This particular issue has also been discussed [in this comment thread](https://unofficialsf.com/send-better-email-flow-action/#comment-5412379939) on the unofficialsf.com page for this action.

### Steps to reproduce

1.  In a new flow, add the SendBetterEmail action
2.  Supply a To address, Subject, HTML Body, Recipient Record Id, and Related Record Id
3.  Check the box "Save Email as Activity on Recipient Record(s)?"
4.  Do not check the box "Save Email as Task on recipient related record(s)?", just leave it blank as default
5.  Debug the flow, observing the "taskIds" output

### Expected behaviour

There should be no task records created on the related record.

### Actual behaviour

A task record is created on the related record.

### Debug Logs

In this debug run, the box "Save Email as Activity on Recipient Record(s)?" was left unchecked by default.

```
SENDBETTEREMAIL (APEX): Send_Email
Inputs:
HTMLbody = {!TemplateBody} (<p>Hello, this is a test email.</p>)
recordId = {!VarOppID} (0067h00000BGZ3ZAAX)
saveAsActivity = true
SendTOthisOneEmailAddress = {!VarEmailToSendTo} (***removed***)
subject = Test Email
templateTargetObjectId = {!VarContactID} (0037h00000SweahAAB)
Outputs:
taskErrors ([])
templateUsed (null)
taskIds ([00T7h00000BkcZ3EAJ])
errors (null)
isSuccess (true)
```

**Comment by jdpond** [comment]
Just Putting this out there so I see it in the future:

This is a TL;DR trying to figure out how to default a Boolean Value of NULL to TRUE (versus FALSE). Needed because the first time a NEW parameter is encountered (either in the APEX Invocable action or in the CPE javascript LightningElement), it should be set to TRUE if it has never been initialized.  Otherwise, a new Boolean parameter will always default to NULL in CPE if it has been exposed as a CHECKBOX - which can (and will) cause backward compatibility issues since if used, would have a default value of FALSE.
If this observation seems consistent, then how do I initialize a new Boolean value to TRUE and sustain FALSE when using CHECKBOX?
It turns out that the value of CHECKBOX is either TRUE or NULL.  Does not seem to be settable to FALSE.
This is apposed with Boolean which can be TRUE, FALSE or NULL.
 Here was the discovery process in CPE:
Use known Boolean parameters (in this case, saveAsActivity and saveAsTask
Capture their value on initiation
Change saveAsTask to TRUE (To use as a reference)
Change saveAsActivity to TRUE and back again to FALSE
During each of these changes capture the parameters for the dispatch event configuration_editor_input_value_changed
Close the CPE ("Done")
Re-open the CPE and examine their values on initiation of the CPE
Results:
Unchecked values are always "null" at initiation (Start of CPE, LightningElement instantiation)
They are set to TRUE via the configuration_editor_input_value_changed event when checked
They are set to FALSE via the configuration_editor_input_value_changed event when unchecked
HOWEVER, Boolean values of FALSE are converted to NULL in the lightning-input component and appear that way in subsequent observation upon instantiation of the LightningElement?

**Comment by jdpond** [comment]
This issue may be the above.  I'm going to go back and modify the CPE to use @ericrsmith35  new Checkbox Component for Custom Property Editors. While I have the time to do the mods, do not have the time to do a thorough test.   Any chance you could help out on the testing @Garywoo?

**Comment by jdpond** [comment]
This update would be made for:

1. - saveAsActivity
2. - saveAsTask
3. - bcc
4. - UseSalesforceSignature

**Comment by Garywoo** [comment]
Thanks for the insight @jdpond. I'd be happy to test the updated checkbox component behaviour in this action.

**Comment by jdpond** [comment]
Fix the remainder of above.  Process is as follows.  This assumes the other code specified in the component have been added (see example in sendBetterEmailCPE.js relative to checkboxes)

1. add each cb_* to SendBetterEmailRequest
2. add each cb_* to sendBetterEmailCPE.js
3. change each in sendBetterEmailCPE.html to use c-fsc_flow-checkbox

example for 1: 
```
	@invocableVariable(description='!(Defaults to True unless recordId/whatId is null)')
	@AuraEnabled
	public String cb_saveAsTask;
```

example for 2:
`		cb_saveAsTask: {value: 'CB_FALSE', dataType: null, isCollection: false, default: null, label: '!Save Email as Task on recipient related record(s)?'},
`
example for 3:
```
<!--
				<lightning-input name="saveAsTask" label={inputValues.saveAsTask.label} type="checkbox"
					checked={inputValues.saveAsTask.value} onchange={handleValueChange}>
				</lightning-input>
-->
				<c-fsc_flow-checkbox name="checkbox_sel_saveAsTask"
					label={inputValues.saveAsTask.label}
					field-level-help={inputValues.saveAsTask.helpText}
					checked={inputValues.cb_saveAsTask.value}
					oncheckboxchanged={handleCheckboxChange}>
				</c-fsc_flow-checkbox>

```

**Comment by jdpond** [comment]
@Garywoo Committed these three changes to my fork - if you copy them into your environment over the existing should be able to test.
[Temporary remediation for issues with checkboxes, Fix #702,#831](https://github.com/jdpond/LightningFlowComponents/commit/f4f0d29e54543f0ec6c3ea74b458f5de3bc18b7c)
[force-app/main/default/classes/SendBetterEmailRequest.cls](https://github.com/jdpond/LightningFlowComponents/blob/f4f0d29e54543f0ec6c3ea74b458f5de3bc18b7c/flow_action_components/SendBetterEmail/force-app/main/default/classes/SendBetterEmailRequest.cls)
[force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.html](https://github.com/jdpond/LightningFlowComponents/blob/f4f0d29e54543f0ec6c3ea74b458f5de3bc18b7c/flow_action_components/SendBetterEmail/force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.html)
[force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.js](https://github.com/jdpond/LightningFlowComponents/blob/f4f0d29e54543f0ec6c3ea74b458f5de3bc18b7c/flow_action_components/SendBetterEmail/force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.js)

**Comment by jdpond** [comment]
@Garywoo after you test, will create a pull request and get a package created.

**Comment by Garywoo** [comment]
@jdpond no problem. Will test it out next week.

**Comment by Garywoo** [comment]
@jdpond I have updated my environment with those 3 files, but the issue is still occuring. The action is still causing a task to be created when the "Save Email as Activity on Recipient Record(s)?" checkbox was left off by default. Toggling it on and off causes it to no longer create tasks.

**Comment by jdpond** [comment]
OK, at least now it is retaining the set value.  Let me look at setting default for this value to false

**Comment by jdpond** [comment]
@Garywoo I hate to ask this, but could you try loading [/force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.js](https://github.com/jdpond/LightningFlowComponents/blob/master/flow_action_components/SendBetterEmail/force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.js) and testing again.  I may have outsmarted myself by setting to "CB_FALSE", which might be interpreted as true.  Reset default to null.

**Comment by Garywoo** [comment]
@jdpond I have updated the file. The same issue is still occuring when the checkbox is left unchecked by default.

**Comment by jdpond** [comment]
// if saveAsTask is null, it will default to whatever saveAsActivity is, but if whatId is null, will set it to false
This condition goes all the way back to sendHTMLEmail and was created as a forward compatibility step.  I am making some more changes now, but could this be the condition you are seeing?

**Comment by Garywoo** [comment]
@jdpond Yes, I believe so. I am setting `saveAsActivity` to true, and providing a `templateTargetObjectId` and a `recordId` value. I'm not explicitly setting `saveAsTask`, but it's assuming that I want to, when in fact I do not. This is fine for the sendHTMLEmail action since all inputs could be explicitly set, but the checkbox inputs in the sendBetterEmail do not allow for this.

I think removing the inherited value for `saveAsTask` from `saveAsActivity` would resolve the issue here.

**Comment by jdpond** [comment]
@Garywoo First.  THANK YOU! your help on this has been magnificent and deeply appreciated.
I hate to sound like Microsoft here, but that behavior is actually a FEATURE.  When sendHTMLEmail was originally written, the task was automatically also attached (if possible) as a task by default, and to NOT do so, would default the saveAsTask to the value of saveAsActivity.  When we moved forward, we decided to keep that behavior so that ohana who were dependent on this behavior would not see a sudden change when they did an upgrade.  This was debated and a path chosen.  While this is documented, it obviously causes confusion - even I didn't remember it until I went and looked today and pulled the above comment directly from the code (That comment had been inserted in 2019). 

On the more positive side, your discovery exposed several other issues resultant from years of evolution - including the retention of FALS **AND** null in several parameters (instead of only TRUE) and the fact that massEmailMessage now requires explicit false in saveAsActivity.  I think the latter is a Summer '21 'enhancement', so I've updated the code.

You have served your community well and thank you.

**Comment by jdpond** [comment]
@Garywoo Could I ask one more favor and check [/force-app/main/default/classes/SendBetterEmail.cls](https://github.com/jdpond/LightningFlowComponents/blob/master/flow_action_components/SendBetterEmail/force-app/main/default/classes/SendBetterEmail.cls).  I made a set of final updates there and would appreciate a second testing before requesting the pull.

**Comment by Garywoo** [comment]
@jdpond Thanks for the insight and the gracious prise.

I updated the class, crossed all my fingers and toes, then re-ran my tests steps. Unfortunately however, the unwanted task was still created.

**Comment by jdpond** [comment]
@Garywoo While we can't correct it without backward compatibility issues, I was able to at least update the CPE so that it appears the way it really is.  Load these three and give it another try?
[force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.html](https://github.com/jdpond/LightningFlowComponents/blob/master/flow_action_components/SendBetterEmail/force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.html)
[force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.js](https://github.com/jdpond/LightningFlowComponents/blob/master/flow_action_components/SendBetterEmail/force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.js)
[force-app/main/default/classes/SendBetterEmail.cls](https://github.com/jdpond/LightningFlowComponents/blob/master/flow_action_components/SendBetterEmail/force-app/main/default/classes/SendBetterEmail.cls)

**Comment by Garywoo** [comment]
@jdpond I've updated the code, and have the following observations:

1.  Upon adding the action, and setting the fields as described in my above replication steps, the 'Save Email as Task' field was left unchecked by default.
2.  Debugging the action showed that tasks were still being created.
3.  Upon editing the action, I could see that 'Save Email as Task' had now become checked, even though I did not do this.
4.  I unchecked the 'Save Email as Task' box, saved, then debugged. Tasks were no longer being created.

I see what you are trying to do with the CPE, making it represent the actual behaviour it will take, however the initial state of the checkbox when setting up the action should also reflect this, not just upon editing an existing action.

If the 'Save Email as Task' box become checked in the CPE as soon as I checked 'Save Email as Activity', when there is a "Related Record Id" field value present, then this would help users understand the predicted behaviour much more clearly. They must still be able to uncheck the box after it's been automatically checked (without closing and re-editing the action), to prevent unwanted tasks from being created.

**Comment by jdpond** [comment]
@Garywoo Thanks, but unfortunately, I think that's the best we can do - which is make it reflect the actual state in the editor.  What is an undesirable characteristic for you would cause an unpredicted (and un-understandable) change for others who have systems already in production. 

Looking at CPE for part 2 above "If the 'Save Email as Task' box become checked in the CPE as soon as I checked 'Save Email as Activity', when there is a "Related Record Id" field value present, then this would help users understand the predicted behaviour much more clearly. They must still be able to uncheck the box after it's been automatically checked (without closing and re-editing the action), to prevent unwanted tasks from being created."

**Comment by jdpond** [comment]
I just had an idea.  How about if  'Save Email as Activity', when there is a "Related Record Id" automatically sets "Save Email as Task" to false if "Save Email as Task" is uninitialized?

**Comment by Garywoo** [comment]
@jdpond Yeah, I believe your idea would work.

I think having the checkbox always reflect the actual state of the editor is an acceptable compromise. If you can get it to update the state of the 'Save Email as Task' checkbox to accurately reflect what will actually happen, while adding the action, then I think that would be fine.

**Comment by jdpond** [comment]
Note to self:  This is the biggest freak job compensation for an original bad design (mine) that I've ever had to do!

**Comment by Garywoo** [comment]
@jdpond I'm unsure on what the expected outcome is for the 'Save Email as Task' checkbox in the testing scenario.

I've updated the code, and what I'm seeing now is the same as [my last test](https://github.com/alexed1/LightningFlowComponents/issues/831#issuecomment-892565503).

I would be happy with either of the following outcomes when initially adding the action:

1.  When checking 'Save Email as Activity' when there is a "Related Record Id" populated --> 'Save Email as Task' immediately becomes checked. I am then able to uncheck it to prevent a task being created.
2.  When checking 'Save Email as Activity' when there is a "Related Record Id" populated --> 'Save Email as Task' remains unchecked, and no task is created.

**Comment by jdpond** [comment]
My bad - you are right - the only difference was that the changes would persist - instead of leaving defaults.  Since you've done so much work on this, which would you prefer from above (1 or 2).  Equal amount of work to implement.

**Comment by Garywoo** [comment]
I would prefer outcome 2. I think your suggested solution should work.

**Comment by jdpond** [comment]
OK, hopefully last change on this:
if 'Save Email As Activity' is clicked if 'Save Email as Task' is null, it will set it to false
[force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.html](https://github.com/jdpond/LightningFlowComponents/blob/master/flow_action_components/SendBetterEmail/force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.html)
[force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.js](https://github.com/jdpond/LightningFlowComponents/blob/master/flow_action_components/SendBetterEmail/force-app/main/default/lwc/sendBetterEmailCPE/sendBetterEmailCPE.js)

**Comment by Garywoo** [comment]
Success! It looks like you've solved it 🎉

I updated the files, and now the outcome plays out exactly like I described in 2 above. No more unexpected tasks!

Thanks so much for your diligent work on this @jdpond! It's an overall a fantastic action that gets used hundreds of times a day in our org. I couldn't live without it. Now if only you could solve my other issue #832, I promise to leave you alone for a while 😁
