### ISSUE TITLE
SendBetterEmail - SendBetterEmailAddAttachmentToEmail - Attachments are not visible in Activity EmailMessage

### ISSUE THREAD

**Issue by michael-eigenherd** [alexed1/LightningFlowComponents#887]
### Steps to reproduce

1. Set up E-Mail sending such that `mail.setSaveAsActivity(true)` and `mail.setWhatId(recordId)` are set, wherein `recordId` is for example an Opportunity. Add an attachment to the email.
2. The sent EmailMessage will then be visible in the Opportunity's Activity Feed

### Expected behaviour
The attachments should be present in the EmailMessage activity.

### Actual behaviour
There are no attachments, even though the mail arrived with all selected attachments intact.

### Cause & Recommendation

In the apex class `SendBetterEmailAddAttachmentToEmail` we assemble the attachments by hand and use `mail.setFileAttachments(attachments);` to attach them to the email. This will result in missing attachments in the activity.

If we instead use `mail.setEntityAttachments(ids)`, the attachments will be present in the activity.

The source of each attachment always is a `ContentVersion`, so there is no direct technical limitation in using `setEntityAttachments` with these CVs instead. 

I could not ascertain any further side effects or downsides this might have.

**Comment by jdpond** [comment]
@michael-eigenherd This is the way it currently works - but believe this is a valid enhancement request.   Would like input from the community as to whether or not this should be a triggered option (e.g., another parameter to "save attachments with activity" checkbox) or just the default behavior.   Also note to self, this should be addressed at the same time as #832 since there are correlations in matching activities to an individual email.

**Comment by michael-eigenherd** [comment]
Hey @jdpond. Thank you for your answer. 
I don't suppose there would be a use-case in wanting attachments not be present in the activity.
They are already in the system as a ContentDocument; it is just the relationship that is missing.
Thanks.

**Comment by jdpond** [comment]
Good point - hadn't had my first cup of coffee yet.  Not duplicating the content, only the CDL to it - the problem will be building the CDL collection for each activity, then doing a single insert - activities and tasks are a bit (well a lot) of a mess right now so getting the associations right is a bit tricky.  Will take this on.

**Comment by michael-eigenherd** [comment]
I have this working locally by simply using `mail.setEntityAttachments()` instead of `mail.setMailAttachments()`. Salesforce takes care of everything. The CDL collection is already present in the method, as well as the corresponding ContentVersion IDs. If you want I can share my solution, and you can adapt it as needed. Or make a PR.
Thank you

**Comment by jdpond** [comment]
@michael-eigenherd Always looking for help maintaining this component - so if you're interested, it would probably mean adjusting to use mail.setEntityAttachments(ids) instead of mail.setFileAttachments in SendBetterEmailAddAttachmentToEmail.cls.  This could also greatly simplify that module - so it may have many advantages.

Keep in mind, how would this impact existing systems?  (May just need documentation changes, but if it changes visual appearance in emails or would require  modification to existing flows . . .)

If you would like to take this on, I will give you full access to the branch I'm using for the next release, https://github.com/jdpond/LightningFlowComponents

**Comment by michael-eigenherd** [comment]
I created a PR here: https://github.com/jdpond/LightningFlowComponents/pull/1
I also created one pointing back to the main repository. 
You can close whichever one you deem unnecessary. I wasn't sure.

Thank you
